### PR TITLE
Version 1.5.3

### PR DESCRIPTION
**Pull request by Sandokaaan**
Upgrade to version 1.5.3
    elimination of false positive virus alerts for Windows wallet
    release wallet for Mac OSX
    blockchain protection bugfix
    new chechpoints
    stable node IPs hardcoded as node seeds
    new webpage address in gui wallet logo

### CODE REVIEW

**Comment by zongyongge** [comment]
thanks your work for eac  very much,!
good luck.
one eac  Volunteers

**Comment by guodong888** [comment]
谢谢你对EAC所做的一切！衷心祝福EAC能够不停壮大！

**Comment by guodong888** [comment]
Thank you for everything that EAC has done! Sincerely wish EAC can continue to grow!

**Comment by zongyongge** [comment]
You big guys, suggest technical reference LTC,BTC,BLK,DASH,DCR and other block chain project idea, let the earth currency become high-quality competition currency, try to do more industry application. 

There is money in the hand, the heart is not panic, the people, the gold can be broken. We EAC Earth holders are humble point, we all unite to develop mutual benefit, develop publicity and operational applications, with the global developers to promote the world's currency for the international economy to help, EAC Earth currency is the Earth's people's digital currency.
newearthcoin.com/earthcoin.io/earthcoin.cc/earthcoin.top/earthcoin.io/eaczg.com/Thank you. Best wishes for good luck.
--------------------------------------------------------------------------------
各位大佬，建议技术上参考LTC,BTC,BLK,DASH,DCR等区块链项目的思路,让地球币成为优质的竞争币种，尽力去做更多行业的应用。

手里有币，心中不慌，齐心者，金可断。我们EAC地球持有人 都谦让一点，大家都团结起来，发展互助共赢，开发宣传运营应用，同全球开发者一起促进地球币为世界经济提供助力，EAC地球币是地球人民的数字货币。
newearthcoin.com/ earthcoin.io/ earthcoin.cc/ earthcoin.top/ earthcoin.io/ eaczg.com/谢谢。祝福好运常伴。

**Comment by guodong888** [comment]
赞赞赞，非常感谢各位所做的努力，期待手机钱包早日发布！

**Comment by guodong888** [comment]
Like praise, thank you very much for your efforts, looking forward to the early release of mobile wallet!

赞赞赞，非常感谢各位所做的努力，期待手机钱包早日发布！

**Comment by zongyongge** [comment]
eac 2018
thanks all for eac!!!

**Comment by zongyongge** [comment]
This app is the Chinese Feimi eldest brother they used to get the mobile phone Android version of the wallet interface, see if you can use, in the email attachment, have send , thank you.

[这个APP是华人飞米大哥 他们以前弄的手机安卓版本钱包界面，看看能不能用上，在邮件附件里面，已经发送了，谢谢。

**Comment by guodong888** [comment]
Firmly believe, firm, adhere to, adhere to, believe that the earth will be better and better under the efforts of all walks of life!

**Comment by uncchain** [comment]
thanks your work for eac very much,! !!
Hope you can develop the earth currency upgrade to the latest technology.
good luck.
one eac Volunteers

**Pull request merged**
